version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: credit_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: credit_backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - ALPHA_VANTAGE_KEY=${ALPHA_VANTAGE_KEY:-demo}
      - NEWS_API_KEY=${NEWS_API_KEY:-}
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./app:/app/app:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis_data:

networks:
  default:
    name: credit_network